### ISSUE TITLE
[HELP] tens of thousands of log entries and stopped working

### ISSUE THREAD

**Issue by Neobond** [flmorg/cleanuperr#109]
### Before submitting a help request, I have:

- [x] Reviewed the documentation.
- [x] Ensured I am using ghcr.io/flmorg/cleanuperr docker repository.
- [x] Ensured I am using the latest version.
- [x] Enabled debug logging.

### How can we help?

I got it working with the assistance of the dev here, and did not change anything. I noticed a couple of episodes stuck on Sonarr due to dangerous files, and checked cleanuperr's logs only to find over 86,000 lines and a group of messages that repeats every 2 minutes (below)

pls help. I stopped and started the container. same issue. (I have now stopped it).

![Image](https://github.com/user-attachments/assets/3b51c732-6a3d-4805-8ae3-3c952568273c)

![Image](https://github.com/user-attachments/assets/9cf6e3df-2b51-4ac4-8b5e-5baa324eaf60)

The log file is 21.1mb so I was unable to attach it, but I can provide more info if needed.

**Comment by Flaminel** [comment]
Are you using a VPN? It seems that qBittorrent is unreachable by cleanuperr.

**Comment by Neobond** [comment]
Yes, it is connected with gluetun, but I specified the local IP like with sonarr and radarr

```
version: "3.3"
services:
  cleanuperr:
    image: ghcr.io/flmorg/cleanuperr:latest
    container_name: cleanuperr
    restart: unless-stopped
    volumes:
      - /volume1/docker/cleanuperr/logs:/var/logs
      - /volume1/docker/cleanuperr/ignored.txt:/ignored.txt
      - /volume1/docker/cleanuperr/blacklist.txt:/blacklist.txt
    environment:
      - TZ=Europe/Amsterdam
      - DRY_RUN=false
      - LOGGING__LOGLEVEL=Information
      - LOGGING__FILE__ENABLED=false
      - LOGGING__FILE__PATH=/var/logs/
      - LOGGING__ENHANCED=true
      - TRIGGERS__QUEUECLEANER=0 0/5 * * * ?
      - TRIGGERS__CONTENTBLOCKER=0 0/5 * * * ?
      - TRIGGERS__DOWNLOADCLEANER=0 0 * * * ?
      - QUEUECLEANER__ENABLED=true
      - QUEUECLEANER__IGNORED_DOWNLOADS_PATH=/ignored.txt
      - QUEUECLEANER__RUNSEQUENTIALLY=true
      - QUEUECLEANER__IMPORT_FAILED_MAX_STRIKES=5
      - QUEUECLEANER__IMPORT_FAILED_IGNORE_PRIVATE=false
      - QUEUECLEANER__IMPORT_FAILED_DELETE_PRIVATE=false
      - QUEUECLEANER__IMPORT_FAILED_IGNORE_PATTERNS__0=title mismatch
      - QUEUECLEANER__IMPORT_FAILED_IGNORE_PATTERNS__1=manual import required
      - QUEUECLEANER__STALLED_MAX_STRIKES=5
      - QUEUECLEANER__STALLED_RESET_STRIKES_ON_PROGRESS=false
      - QUEUECLEANER__STALLED_IGNORE_PRIVATE=false
      - QUEUECLEANER__STALLED_DELETE_PRIVATE=false
      - CONTENTBLOCKER__ENABLED=true
      - CONTENTBLOCKER__IGNORED_DOWNLOADS_PATH=/ignored.txt
      - CONTENTBLOCKER__IGNORE_PRIVATE=false
      - CONTENTBLOCKER__DELETE_PRIVATE=false
      - DOWNLOADCLEANER__ENABLED=true
      - DOWNLOADCLEANER__IGNORED_DOWNLOADS_PATH=/ignored.txt
      - DOWNLOADCLEANER__DELETE_PRIVATE=false
      - DOWNLOADCLEANER__CATEGORIES__0__NAME=tv-sonarr
      - DOWNLOADCLEANER__CATEGORIES__0__MAX_RATIO=-1
      - DOWNLOADCLEANER__CATEGORIES__0__MIN_SEED_TIME=0
      - DOWNLOADCLEANER__CATEGORIES__0__MAX_SEED_TIME=240
      - DOWNLOADCLEANER__CATEGORIES__1__NAME=radarr
      - DOWNLOADCLEANER__CATEGORIES__1__MAX_RATIO=-1
      - DOWNLOADCLEANER__CATEGORIES__1__MIN_SEED_TIME=0
      - DOWNLOADCLEANER__CATEGORIES__1__MAX_SEED_TIME=240
      - DOWNLOAD_CLIENT=none
      # OR
      - DOWNLOAD_CLIENT=qBittorrent
      - QBITTORRENT__URL=http://192.168.178.11:8090
      - QBITTORRENT__USERNAME=admin
      - QBITTORRENT__PASSWORD=<redacted>
      # OR
      # - DOWNLOAD_CLIENT=deluge
      # - DELUGE__URL=http://localhost:8112
      # - DELUGE__PASSWORD=testing
      # OR
      # - DOWNLOAD_CLIENT=transmission
      # - TRANSMISSION__URL=http://localhost:9091
      # - TRANSMISSION__USERNAME=test
      # - TRANSMISSION__PASSWORD=testing
      - SONARR__ENABLED=true
      - SONARR__SEARCHTYPE=Episode
      - SONARR__BLOCK__TYPE=blacklist
      - SONARR__BLOCK__PATH=/blacklist.txt
      - SONARR__INSTANCES__0__URL=http://192.168.178.11:8989
      - SONARR__INSTANCES__0__APIKEY=<redacted>
      
      - RADARR__ENABLED=true
      - RADARR__BLOCK__TYPE=blacklist
      - RADARR__BLOCK__PATH=/blacklist.txt
      - RADARR__INSTANCES__0__URL=http://192.168.178.11:7878
      - RADARR__INSTANCES__0__APIKEY=<redacted>
```

**Comment by Flaminel** [comment]
Unfortunately I don't think this is something that cleanuperr can fix by itself and I don't have a VPN at the moment to test it. You have to make sure your setup is correct and cleanuperr's container can connect to the qBit instance. As mentioned in #41, [this comment](https://github.com/flmorg/cleanuperr/issues/41#issuecomment-2606749311) might help you get it back up. If you have  any idea on how I could reproduce this problem without a VPN, or anything at all really, I'm all open to suggestions.

**Comment by Neobond** [comment]
> Unfortunately I don't think this is something that cleanuperr can fix by itself and I don't have a VPN at the moment to test it. You have to make sure your setup is correct and cleanuperr's container can connect to the qBit instance. As mentioned in [#41](https://github.com/flmorg/cleanuperr/issues/41), [this comment](https://github.com/flmorg/cleanuperr/issues/41#issuecomment-2606749311) might help you get it back up. If you have any idea on how I could reproduce this problem without a VPN, or anything at all really, I'm all open to suggestions.

Thanks for your quick responses to me, really. Do you think adding network: host might solve it? (as cleanuperr relies on local IPs _anyway_. Maybe I can add Bridge network via portainer and see if that helps.

Edit: btw my qbit/gluetun compose, and sonarr and radarr arrs compose all use "network_mode: synobridge" I think I will be able to fix this simply by adding cleanuperr to the arrs compose so it will be in the same docker network.

**Comment by Flaminel** [comment]
No worries! I'm here to help as best as I can. Let me know if you succeed by changing the network mode, please!

**Comment by Neobond** [comment]
I added it at the top and started the container and it started without error.

I am sad I removed the two bad downloads, so I cannot test it right now. I will have to keep an eye on the logs to see if it happens again. (when I removed the two bad downloads manually from Sonarr, the "good" files were quickly downloaded).

Thanks for debugging the issue!

```
version: "3.3"
services:
  cleanuperr:
    image: ghcr.io/flmorg/cleanuperr:latest
    container_name: cleanuperr
    network_mode: synobridge
    restart: unless-stopped
```

![Image](https://github.com/user-attachments/assets/63b97675-1cfb-4e2b-93b1-3f7ebe1d79da)
