### ISSUE TITLE
[FEATURE] downloads stuck on metadata

### ISSUE THREAD

**Issue by jgeorge1983** [flmorg/cleanuperr#111]
### Before submitting a bug report, I have:

- [x] Reviewed the documentation.
- [x] Ensured I am using ghcr.io/flmorg/cleanuperr docker repository.
- [x] Ensured I am using the latest version.
- [x] Enabled debug logging.

### What is the behavior?

If we have a download that is stuck downloading metadata, and its sat for a while, can we get that removed automatically?

[2025-04-03 14:10:01.343 INF]    [QueueCleaner] [Lidarr] 1 items found in queue | http://192.168.4.204:8686/
[2025-04-03 14:10:01.354 INF]    [QueueCleaner] [Lidarr] skip | 35665fe2b71b7bf311d8a53b0917b34050ad8e13

Example from the log

Not sure how easy to implement it?

### Which operating system do you use?

Windows

### What type of deployment do you use?

Docker container

### Relevant log output

```shell

```

**Comment by Flaminel** [comment]
You didn't actually review the docs, right? Please share your configuration, your download client and a picture of the status of the download, excluding sensitive information.

**Comment by jgeorge1983** [comment]
```
cleanuperr:
    image: ghcr.io/flmorg/cleanuperr:latest  
    container_name: cleanuperr
    environment:
      - TRIGGERS__QUEUECLEANER=0 0/5 * * * ?
      - CONTENTBLOCKER__ENABLED=true
      - CONTENTBLOCKER__BLACKLIST__ENABLED=true
      - CONTENTBLOCKER__BLACKLIST__PATH=https://raw.githubusercontent.com/flmorg/cleanuperr/refs/heads/main/blacklist        
      - DOWNLOAD_CLIENT=qBittorrent       
      - QBITTORRENT__URL=http://192.168.5.15:8082
      - QBITTORRENT__USERNAME=<UN>
      - QBITTORRENT__PASSWORD=<PW>
      - SONARR__ENABLED=true
      - SONARR__BLOCK__TYPE=blacklist      
      - SONARR__INSTANCES__0__URL=http://192.168.4.204:8989
      - SONARR__INSTANCES__0__APIKEY=
      - RADARR__ENABLED=true
      - RADARR__BLOCK__TYPE=blacklist      
      - RADARR__INSTANCES__0__URL=http://192.168.4.204:7878
      - RADARR__INSTANCES__0__APIKEY=
      - LIDARR__ENABLED=true
      - LIDARR__BLOCK__TYPE=blacklist      
      - LIDARR__INSTANCES__0__URL=http://192.168.4.204:8686
      - LIDARR__INSTANCES__0__APIKEY=    
    volumes:
      - /home/pi/docker/vpn-apps/cleanuperr/appdata:/config      
```

![Image](https://github.com/user-attachments/assets/e29cda26-b826-48a2-9310-47ea45f98423)

I'm using qbittorrent

Appologies did i miss something about this in the documents?
